// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3a0q3ZdNPFEg8cqeAHK6hbufxFYMvhQs',
    appId: '1:1067109291316:web:3943b64eeb2959aa410161',
    messagingSenderId: '1067109291316',
    projectId: 'zhet-9211c',
    authDomain: 'zhet-9211c.firebaseapp.com',
    storageBucket: 'zhet-9211c.firebasestorage.app',
    measurementId: 'G-WX5T4JFZHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHhCrZ5RtnoBKekncslVy7IDamEiApS8',
    appId: '1:1067109291316:android:83f8db5133b8ea6c410161',
    messagingSenderId: '1067109291316',
    projectId: 'zhet-9211c',
    storageBucket: 'zhet-9211c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArjvkkhz_FqUMsO_6htfSMsPkMkZ1Yrdw',
    appId: '1:1067109291316:ios:a51cee94da8fc472410161',
    messagingSenderId: '1067109291316',
    projectId: 'zhet-9211c',
    storageBucket: 'zhet-9211c.firebasestorage.app',
    iosBundleId: 'com.example.zhet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArjvkkhz_FqUMsO_6htfSMsPkMkZ1Yrdw',
    appId: '1:1067109291316:ios:a51cee94da8fc472410161',
    messagingSenderId: '1067109291316',
    projectId: 'zhet-9211c',
    storageBucket: 'zhet-9211c.firebasestorage.app',
    iosBundleId: 'com.example.zhet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3a0q3ZdNPFEg8cqeAHK6hbufxFYMvhQs',
    appId: '1:1067109291316:web:b2a8bdd5ed4ea491410161',
    messagingSenderId: '1067109291316',
    projectId: 'zhet-9211c',
    authDomain: 'zhet-9211c.firebaseapp.com',
    storageBucket: 'zhet-9211c.firebasestorage.app',
    measurementId: 'G-WP01M85DJQ',
  );
}
